### ISSUE TITLE
Pin spacing 

### ISSUE THREAD

**Issue by ilium007** [stasiselectronics/MicroBBPS#5]
What is the exact distance between the outer pins? Thanks.

**Comment by ChandlerMcCowan** [comment]
Hi!

The outer pins that interface with a breadboard are 1.9 inches apart.

This is the same on the integrated version as well.

Hope this helps and feel free to ask any follow up questions!

![2021 08 14](https://user-images.githubusercontent.com/7789383/129444132-182df701-4240-4a60-b293-c6423dd0f05e.png)

**Comment by ilium007** [comment]
Thanks!

**Comment by ilium007** [comment]
Sorry, one more question. How do you do those awesome reverse labels (3.3v / 5v)

**Comment by ChandlerMcCowan** [comment]
No worries,

I use Inkscape to draw some of the artwork and then import it into KICAD as a footprint that just has silkscreen on it.

That makes it possible to use extra fonts, and draw more elaborate shapes.

Here's a video tutorial for [cutting text out of shapes in inkscape](https://www.youtube.com/watch?v=Men1K2oMq8g)

Keysight recently did a video about PCB artwork, I haven't watched it yet but [here it is](https://www.youtube.com/watch?v=0lomLQOFW8U)

**Comment by ilium007** [comment]
So good! Thanks again.

**Comment by ilium007** [comment]
I knew I had 'liked' something similar on Twitter a while back and just went back through my history and found it! 

https://github.com/gregdavill/KiBuzzard

![Uploading C5B3B605-FD92-488B-B635-5E0F1B7A76FB.jpeg…]()

**Comment by ilium007** [comment]
Works beautifully for simple text!

<img width="565" alt="image" src="https://user-images.githubusercontent.com/732766/129446518-37f67a39-7ebf-4913-aa9b-51f02debde91.png">

**Comment by ChandlerMcCowan** [comment]
Nice! Looks good!
